version: "3"

services:
  backend:
    image: node:16
    container_name: backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    env_file:
      - .env.template
    environment:
     - DATABASE_URL=${DATABASE_URL}
     - DATABASE_NAME=${DATABASE_NAME}
     - HOST=${HOST}
     - PORT=${PORT}
    networks:
      - fullstack
    depends_on:
      - db

  db:
    image: mongo
    container_name: db
    ports:
      - 27017:3000
    env_file:
      - .env.template
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    
  dbexpress:
    image: mongo-express
    container_name: dbexpress
    ports:
      - 8081:3000
    env_file:
      - .env.template
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:27017