version: "3"

services:
  backend:
    image: node:16
    container_name: backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    environment:
     - DATABASE_URL=${DATABASE_URL}
     - DATABASE_NAME=${DATABASE_NAME}
     - HOST=${HOST}
     - PORT=${PORT}
    networks:
      - fullstack
    depends_on:
      - db

  db:
    image: mongo
    container_name: db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}