version: "3"

services:
  backend:
    image: backend-topic
    container_name: backend
    ports:
      - 5000:5000
    environment:
     - DATABASE_URL=mongodb://localhost:27017
     - DATABASE_NAME=opicstoreDb
     - HOST=localhost
     - PORT=5000
    networks:
      - fullstack
    depends_on:
      - db
    
  frontend:
    image: frontend-topic
    container_name: frontend
    ports:
      - 3000:3000
    environment:
      - HOST=localhost
      - PORT=3000
    networks:
      - fullstack
    depends_on:
      - backend
    
  db:
    image: db-topic
    container_name: db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    
  dbexpress:
    image: mongo-express
    container_name: dbexpress
    ports:
      - 3001:3000
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@db:27017
    depends_on:
      - db

networks:
  fullstack:
    driver: bridge