  version: "3.8"
  
  services:
    travel_db:
      container_name: travel_db
      image: mysql:latest
      environment:
        - MYSQL_DATABASE=devopstravel
        - MYSQL_USER=codeuser
        - MYSQL_PASSWORD=codepass
        - MYSQL_ROOT_PASSWORD=codepass
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
      volumes: 
         - "./database:/docker-entrypoint-initdb.d"
      networks: 
          - travel_lamp
    
    www:
      container_name: travel_www
      depends_on: 
        - travel_db
      image: httpd:alpine
      volumes: 
        - ".:/var/www/html"
      ports:
          - "80:80"
      networks:
        - travel_lamp
    
    phpmyadmin:
      container_name: travel_phpmyadmin
      depends_on: 
        - travel_db
      image: phpmyadmin/phpmyadmin
      ports: 
        - "8081:8081"
      environment:
        - PMA_HOST=travel_db
        - PMA_PORT=3306
      networks:
        - travel_lamp
  
  networks: 
    travel_lamp:
      driver: bridge