  version: "3.8"
  
  services:
    database:
      container_name: travel_db
      image: mysql
      build: 
        context: ./database
        dockerfile: dockerfile
      environment:
        MYSQL_ROOT_PASSWORD: codepass
        MYSQL_DATABASE: devopstravel
        MYSQL_USER: codeuser
        MYSQL_PASSWORD: codepass
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        MYSQL_RANDOM_ROOT_PASSWORD: 1
      ports:
        - "3306:3306"
      networks: 
          - travel_lamp
    
    web:
      container_name: travel_www
      depends_on: 
        - database
      image: httpd
      build: 
        context: ./web
        dockerfile: dockerfile
      ports:
          - "80:80"
      networks:
        - travel_lamp
    
    phpmyadmin:
      container_name: travel_phpmyadmin
      depends_on: 
        - database
      image: phpmyadmin
      build: 
        context: ./phpmyadmin
        dockerfile: dockerfile 
      ports: 
        - "8080:80"
      networks:
        - travel_lamp
  
  networks: 
    travel_lamp:
      driver: bridge