  version: "3.8"
  
  services:
    travel_db:
      container_name: travel_db
      image: mysql
      build: 
        context: ./database
        dockerfile: Dockerfile
      ports:
        - "3306:3306"
      networks: 
          - travel_lamp
    
    www:
      container_name: travel_www
      depends_on: 
        - travel_db
      image: httpd
      build: 
        context: ./web
        dockerfile: Dockerfile
      ports:
          - "80:80"
      networks:
        - travel_lamp
    
    phpmyadmin:
      container_name: travel_phpmyadmin
      depends_on: 
        - travel_db
      image: phpmyadmin
      build: 
        context: ./phpmyadmin
        dockerfile: Dockerfile 
      ports: 
        - "8080:80"
      networks:
        - travel_lamp
  
  networks: 
    travel_lamp:
      driver: bridge