  version: "3.8"
  
  services:
    database:
      container_name: travel_db
      image: mysql
      build: 
        context: ./database
        dockerfile: dockerfile
      env_file: 
        - ./database/password.env
      ports:
        - "3306:3306"
      networks: 
          - travel_lamp
    
    web:
      container_name: travel_www
      depends_on: 
        - database
      image: httpd
      build: 
        context: ./web
        dockerfile: dockerfile
      ports:
          - "80:80"
      restart: always
      networks:
        - travel_lamp
    
    phpmyadmin:
      container_name: travel_phpmyadmin
      depends_on: 
        - database
      image: phpmyadmin
      build: 
        context: ./phpmyadmin
        dockerfile: dockerfile 
      ports: 
        - "8080:80"
      networks:
        - travel_lamp
  
  networks: 
    travel_lamp:
      driver: bridge