FROM php:7.2-apache

COPY ./public-html/ /var/www/html/
#RUN sed -i 's/DirectoryIndex index.html/DirectoryIndex index.php index.html/' /usr/local/apache2/conf/httpd.conf
RUN sed -i 's/""/"codepass"/g' /var/www/html/config.php

RUN docker-php-ext-install mysqli 
RUN docker-php-ext-enable mysqli
